import type { Creator, SearchTask, TaskLog } from "./types";
import { classifyMockCategory } from "./category-taxonomy";

const baseCreators: Omit<Creator, "id" | "works" | "profileUrl">[] = [
  {
    nickname: "阿城讲古建",
    douyinAccount: "acheng_arch",
    category: "泛知识",
    subcategory: "历史人文",
    bio: "走进老建筑，讲清它背后的城市与人。",
    followers: 8300,
    totalLikes: 126000,
    verticality: 92,
    targetRatio: 88,
    originalityRisk: "低",
    recommendation: "RECOMMENDED",
    tianmuStatus: "NOT_MATCHED",
    finalStatus: "RECOMMENDED_FOR_BD",
    emerging: true,
    keyword: "古建筑背后的故事",
    reasoning: "最近12条作品中有10条围绕古建筑与地方历史，8条包含年代、人物和建筑结构信息。选题稳定、原创出镜概率高，具备搜索和长期查阅价值。",
    avatarColor: "#247a5c",
  },
  {
    nickname: "住小屋的阿梨",
    douyinAccount: "ali_home",
    category: "泛生活",
    subcategory: "家居收纳",
    bio: "小户型改造、收纳和低预算生活实验。",
    followers: 4620,
    totalLikes: 74000,
    verticality: 95,
    targetRatio: 91,
    originalityRisk: "低",
    recommendation: "RECOMMENDED",
    tianmuStatus: "NOT_MATCHED",
    finalStatus: "RECOMMENDED_FOR_BD",
    emerging: true,
    keyword: "小户型收纳方法",
    reasoning: "近期作品持续展示真实改造步骤、预算和使用反馈，信息密度高。粉丝体量较小，但内容方向清晰，适合进入新锐潜力池。",
    avatarColor: "#bd744d",
  },
  {
    nickname: "林律师说法",
    douyinAccount: "law_lin",
    category: "泛知识",
    subcategory: "法律科普",
    bio: "把复杂法律问题讲成普通人听得懂的话。",
    followers: 78000,
    totalLikes: 1560000,
    verticality: 89,
    targetRatio: 86,
    originalityRisk: "低",
    recommendation: "RECOMMENDED",
    tianmuStatus: "MATCHED",
    finalStatus: "ALREADY_IN_TIANMU",
    emerging: false,
    keyword: "普通人法律知识",
    reasoning: "以劳动合同、消费维权和婚姻家庭为主，案例完整且结论明确。天牧返回唯一完全同名结果，默认不进入BD名单。",
    avatarColor: "#426b9b",
  },
  {
    nickname: "小林的城市漫游",
    douyinAccount: "citylin",
    category: "泛生活",
    subcategory: "旅行攻略",
    bio: "用周末走一座城，分享路线、预算与避坑。",
    followers: 24000,
    totalLikes: 390000,
    verticality: 84,
    targetRatio: 79,
    originalityRisk: "低",
    recommendation: "RECOMMENDED",
    tianmuStatus: "REVIEW_REQUIRED",
    finalStatus: "MANUAL_REVIEW",
    emerging: false,
    keyword: "城市小众旅行",
    reasoning: "路线、交通和预算信息完整，近期10条有8条为城市攻略。天牧出现两个完全同名结果，需要人工复核。",
    avatarColor: "#8270a8",
  },
  {
    nickname: "三分钟看电影",
    douyinAccount: "movie_3min",
    category: "其他",
    subcategory: "影视切片",
    bio: "热门电影高能片段。",
    followers: 460000,
    totalLikes: 9900000,
    verticality: 96,
    targetRatio: 12,
    originalityRisk: "高",
    recommendation: "NOT_RECOMMENDED",
    tianmuStatus: "NOT_CHECKED",
    finalStatus: "DO_NOT_CONTACT",
    emerging: false,
    keyword: "影视文学解读",
    reasoning: "近期作品主要为影视原片剪辑，缺少稳定的原创解读与信息增量，存在明显版权和搬运风险。",
    avatarColor: "#a94e4e",
  },
  {
    nickname: "好物严选官",
    douyinAccount: "best_shop_88",
    category: "泛生活",
    subcategory: "商品展示",
    bio: "每天分享超值好物，橱窗同款。",
    followers: 820000,
    totalLikes: 13000000,
    verticality: 72,
    targetRatio: 18,
    originalityRisk: "中",
    recommendation: "NOT_RECOMMENDED",
    tianmuStatus: "NOT_CHECKED",
    finalStatus: "DO_NOT_CONTACT",
    emerging: false,
    keyword: "家居好物",
    reasoning: "作品以商品口播和购买引导为主，缺少可独立成立的教程、测评方法与真实经验，不进入内容候选池。",
    avatarColor: "#9e783a",
  },
  {
    nickname: "AI冷知识工厂",
    douyinAccount: "ai_knowledge_factory",
    category: "泛知识",
    subcategory: "低质AI",
    bio: "每天十条你不知道的冷知识。",
    followers: 13000,
    totalLikes: 190000,
    verticality: 80,
    targetRatio: 52,
    originalityRisk: "高",
    recommendation: "NOT_RECOMMENDED",
    tianmuStatus: "NOT_CHECKED",
    finalStatus: "DO_NOT_CONTACT",
    emerging: false,
    keyword: "历史冷知识",
    reasoning: "视频使用高度重复模板、合成配音和无来源素材，事实表述不稳定，疑似低质量AI批量生产。",
    avatarColor: "#596673",
  },
  {
    nickname: "小周实验室",
    douyinAccount: "zhou_lab",
    category: "泛知识",
    subcategory: "科学科普",
    bio: "在厨房和阳台做普通人也能复现的小实验。",
    followers: 980,
    totalLikes: 11800,
    verticality: 87,
    targetRatio: 83,
    originalityRisk: "低",
    recommendation: "RECOMMENDED",
    tianmuStatus: "NOT_MATCHED",
    finalStatus: "RECOMMENDED_FOR_BD",
    emerging: true,
    keyword: "生活科学实验",
    reasoning: "仅有6条作品，但均为本人演示，步骤完整并解释现象原理。内容质量高于账号体量，标记为新锐潜力作者。",
    avatarColor: "#2e8791",
  },
  {
    nickname: "老陈说点事",
    douyinAccount: "chen_talk",
    category: "泛知识",
    subcategory: "社会观察",
    bio: "聊生活、社会新闻，也记录钓鱼日常。",
    followers: 35000,
    totalLikes: 670000,
    verticality: 46,
    targetRatio: 51,
    originalityRisk: "中",
    recommendation: "REVIEW_REQUIRED",
    tianmuStatus: "NOT_CHECKED",
    finalStatus: "MANUAL_REVIEW",
    emerging: false,
    keyword: "社会观察",
    reasoning: "观点类内容有信息价值，但账号主题跨度较大，近期同时包含钓鱼、家庭记录和新闻评论，需人工确认招募方向。",
    avatarColor: "#626e46",
  },
  {
    nickname: "跟着阿野吃本地",
    douyinAccount: "local_food_ye",
    category: "泛生活",
    subcategory: "地方美食",
    bio: "不只告诉你好不好吃，也说价格、路线和点单方法。",
    followers: 16700,
    totalLikes: 228000,
    verticality: 86,
    targetRatio: 82,
    originalityRisk: "低",
    recommendation: "RECOMMENDED",
    tianmuStatus: "LOGIN_EXPIRED",
    finalStatus: "MANUAL_REVIEW",
    emerging: false,
    keyword: "本地人推荐美食",
    reasoning: "内容包含价格、营业时间、排队情况与点单建议，较普通探店更具决策价值。天牧查询时登录态失效，等待重试。",
    avatarColor: "#c05f43",
  },
];

const extraNames = [
  ["木工阿哲", "手工非遗", "RECOMMENDED"],
  ["宠物医生小许", "宠物知识", "RECOMMENDED"],
  ["小北讲地理", "地理知识", "RECOMMENDED"],
  ["七月读书", "文学解读", "REVIEW_REQUIRED"],
  ["老家新农人", "三农生活", "RECOMMENDED"],
  ["通勤穿搭手册", "穿搭经验", "REVIEW_REQUIRED"],
  ["装修避坑王工", "装修经验", "RECOMMENDED"],
  ["每天一个心理学", "心理知识", "REVIEW_REQUIRED"],
  ["数码实测老郑", "数码测评", "RECOMMENDED"],
  ["车间主任聊汽车", "汽车知识", "RECOMMENDED"],
  ["护肤成分小课", "美妆知识", "RECOMMENDED"],
  ["职场阿文", "职场技能", "RECOMMENDED"],
  ["综艺爆笑社", "综艺切片", "NOT_RECOMMENDED"],
  ["生活随手拍", "生活记录", "NOT_RECOMMENDED"],
  ["旅行搬运站", "旅行攻略", "NOT_RECOMMENDED"],
] as const;

const extras: Omit<Creator, "id" | "works" | "profileUrl">[] = extraNames.map(
  ([nickname, subcategory, recommendation], index) => {
    const recommended = recommendation === "RECOMMENDED";
    const review = recommendation === "REVIEW_REQUIRED";
    return {
      nickname,
      douyinAccount: `mock_creator_${index + 11}`,
      category: subcategory.includes("切片") ? "其他" : index % 3 === 0 ? "泛生活" : "泛知识",
      subcategory,
      bio: `持续分享${subcategory}相关的真实经验与实用信息。`,
      followers: 1200 + index * 6300,
      totalLikes: 16000 + index * 68000,
      verticality: recommended ? 78 + (index % 18) : review ? 52 + index : 24 + index,
      targetRatio: recommended ? 74 + (index % 20) : review ? 49 + index : 16 + index,
      originalityRisk: recommendation === "NOT_RECOMMENDED" ? "高" : review ? "中" : "低",
      recommendation,
      tianmuStatus: recommended ? (index % 5 === 0 ? "MATCHED" : "NOT_MATCHED") : "NOT_CHECKED",
      finalStatus: recommended
        ? index % 5 === 0
          ? "ALREADY_IN_TIANMU"
          : "RECOMMENDED_FOR_BD"
        : review
          ? "MANUAL_REVIEW"
          : "DO_NOT_CONTACT",
      emerging: recommended && index % 4 === 0,
      keyword: `${subcategory}怎么做`,
      reasoning: recommended
        ? `近期作品聚焦${subcategory}，多条内容包含明确步骤、经验或判断依据，具备持续创作与搜索分发价值。`
        : review
          ? `内容方向与目标范围相关，但作品稳定性或原创证据不足，建议人工查看代表作品后确认。`
          : `近期内容缺少稳定的信息增量，且存在切片、搬运或低质量记录风险，不建议进入候选池。`,
      avatarColor: ["#458773", "#6d79a8", "#ad6f58", "#4d7e9e"][index % 4],
    };
  },
);

function makeWorks(name: string, index: number) {
  const titles = [
    `${name}：新手最容易忽略的三个细节`,
    `我用一周验证了这个常见说法`,
    `从真实案例看，应该怎么判断`,
  ];
  return titles.map((title, workIndex) => ({
    id: `work-${index + 1}-${workIndex + 1}`,
    title,
    format: workIndex === 0 ? "教程" : workIndex === 1 ? "经验分享" : "案例分析",
    infoValue: workIndex === 2 ? ("中" as const) : ("高" as const),
    baiduFit: "高" as const,
    likes: 380 + index * 97 + workIndex * 211,
    publishedAt: `2026-07-${String(24 - workIndex).padStart(2, "0")}`,
  }));
}

export const creators: Creator[] = [...baseCreators, ...extras].map((creator, index) => ({
  ...creator,
  category: classifyMockCategory(`${creator.subcategory} ${creator.bio} ${creator.keyword}`),
  id: `creator-${String(index + 1).padStart(2, "0")}`,
  profileUrl: `https://www.douyin.com/user/${creator.douyinAccount}`,
  works: makeWorks(creator.subcategory, index),
}));

export const tasks: SearchTask[] = [
  {
    id: "task-1",
    name: "泛知识新锐作者扫描",
    category: "泛知识",
    keywords: ["历史人物冷知识", "生活科学实验", "普通人法律知识", "古建筑背后的故事"],
    targetRequirement: "寻找有稳定原创表达、内容垂直且具备百度分发价值的新锐知识创作者。",
    resultLimitPerKeyword: 12, worksLimitPerCreator: 6, estimatedApiCalls: 100,
    checkpoint: { keywordIndex: 2, creatorIndex: 17 }, pauseReason: "", failures: [],
    status: "RUNNING",
    progress: 68,
    discovered: 146,
    recommended: 52,
    checked: 31,
    bdReady: 23,
    lastRun: "今天 14:36",
  },
  {
    id: "task-2",
    name: "生活经验与家居KOC",
    category: "泛生活",
    keywords: ["小户型收纳", "租房改造经验", "装修避坑", "生活实用技巧"],
    targetRequirement: "寻找能提供真实经验、明确步骤和可复用生活方法的创作者。",
    resultLimitPerKeyword: 12, worksLimitPerCreator: 6, estimatedApiCalls: 100,
    checkpoint: { keywordIndex: 1, creatorIndex: 8 },
    pauseReason: "检测到天牧登录状态失效，查重环节等待人工登录；内容筛选继续保留。",
    failures: [{ id: "failure-1", creatorName: "跟着阿野吃本地", stage: "TIANMU", errorType: "LOGIN_REQUIRED", message: "天牧登录已失效，需要人工重新登录。", retryCount: 0, status: "PENDING" }],
    status: "PAUSED",
    progress: 43,
    discovered: 89,
    recommended: 34,
    checked: 18,
    bdReady: 12,
    lastRun: "今天 11:08",
  },
  {
    id: "task-3",
    name: "城市旅行与地方美食",
    category: "泛生活",
    keywords: ["城市小众旅行", "本地人推荐美食", "周末路线攻略"],
    targetRequirement: "寻找路线、预算和决策信息完整，适合长期运营建联的本地生活创作者。",
    resultLimitPerKeyword: 12, worksLimitPerCreator: 6, estimatedApiCalls: 75,
    checkpoint: { keywordIndex: 3, creatorIndex: 0 }, pauseReason: "", failures: [],
    status: "COMPLETED",
    progress: 100,
    discovered: 218,
    recommended: 77,
    checked: 77,
    bdReady: 48,
    lastRun: "昨天 18:20",
  },
];

export const logs: TaskLog[] = [
  { id: "l1", time: "2026-07-27 14:36:18", level: "INFO", module: "抖音搜索", action: "关键词完成", message: "“古建筑背后的故事”发现 24 位作者，去重后新增 11 位。" },
  { id: "l2", time: "2026-07-27 14:34:52", level: "INFO", module: "内容分析", action: "作者完成", message: "阿城讲古建：推荐，目标内容占比 88%，原创风险低。" },
  { id: "l3", time: "2026-07-27 14:33:07", level: "WARN", module: "天牧查重", action: "需要复核", message: "小林的城市漫游：返回 2 个完全同名结果，未自动判断。" },
  { id: "l4", time: "2026-07-27 14:29:44", level: "ERROR", module: "天牧查重", action: "登录失效", message: "检测到百度登录态失效，已暂停后续天牧查询。" },
  { id: "l5", time: "2026-07-27 14:27:10", level: "INFO", module: "账号去重", action: "重复命中", message: "住小屋的阿梨已由“租房改造经验”发现，本次仅追加关键词来源。" },
  { id: "l6", time: "2026-07-27 14:22:36", level: "WARN", module: "内容分析", action: "人工复核", message: "老陈说点事：内容跨度较大，已进入人工复核队列。" },
  { id: "l7", time: "2026-07-27 14:18:03", level: "INFO", module: "任务队列", action: "断点恢复", message: "泛知识新锐作者扫描从第 9 个关键词恢复运行。" },
];
